import {
  SiReact,
  SiFirebase,
  SiMongodb,
  SiTailwindcss,
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiDjango,
  SiFlask,
  SiExpress,
  SiPostgresql,
  SiGit,
  SiGithub,
  SiDocker,
  SiAmazon,
  SiVercel,
  SiSupabase,
  SiSelenium,
  SiStripe,
  SiMapbox,
  SiHeroku,
  SiNextdotjs,
  SiOvh,
  SiJest,
} from "react-icons/si";

import { FaJava, FaNodeJs, FaPython } from "react-icons/fa";

const techIcons = {
  React: SiReact,
  Firebase: SiFirebase,
  MongoDB: SiMongodb,
  "Node.js": FaNodeJs,
  Python: FaPython,
  "Tailwind CSS": SiTailwindcss,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  HTML5: SiHtml5,
  CSS3: SiCss3,
  Django: SiDjango,
  Flask: SiFlask,
  Express: SiExpress,
  PostgreSQL: SiPostgresql,
  Git: SiGit,
  GitHub: SiGithub,
  Docker: SiDocker,
  AWS: SiAmazon,
  Vercel: SiVercel,
  Supabase: SiSupabase,
  Selenium: SiSelenium,
  Stripe: SiStripe,
  Mapbox: SiMapbox,
  Heroku: SiHeroku,
  "Next.js": SiNextdotjs,
  Java: FaJava,
  OVH: SiOvh,
  Jest: SiJest,
};

export default techIcons;
